services:
  web-example:
    build:
      context: ..
      dockerfile: misc/Dockerfile
    platform: linux/amd64
    working_dir: /workspace
    volumes:
      - ..:/workspace
    environment:
      - TF_SERVE_PORT
      - TF_EXAMPLE_TARGET
    ports:
      - "${TF_SERVE_PORT:-8080}:8080"
    command:
      - bash
      - -lc
      - ./misc/build_web.sh
