# Cut binding sources
# Add new files here when creating new bindings
set(MODULE_CUT_SOURCES
  ${CMAKE_CURRENT_LIST_DIR}/boolean.cpp
  ${CMAKE_CURRENT_LIST_DIR}/boolean_int64int6433double3d.cpp
  ${CMAKE_CURRENT_LIST_DIR}/boolean_int64int6433float3d.cpp
  ${CMAKE_CURRENT_LIST_DIR}/boolean_intint33double3d.cpp
  ${CMAKE_CURRENT_LIST_DIR}/boolean_intint33float3d.cpp
  ${CMAKE_CURRENT_LIST_DIR}/boolean_intint6433double3d.cpp
  ${CMAKE_CURRENT_LIST_DIR}/boolean_intint6433float3d.cpp
  ${CMAKE_CURRENT_LIST_DIR}/embedded_intersection_curves.cpp
  ${CMAKE_CURRENT_LIST_DIR}/embedded_intersection_curves_int64int33double3d.cpp
  ${CMAKE_CURRENT_LIST_DIR}/embedded_intersection_curves_int64int33float3d.cpp
  ${CMAKE_CURRENT_LIST_DIR}/embedded_intersection_curves_int64int6433double3d.cpp
  ${CMAKE_CURRENT_LIST_DIR}/embedded_intersection_curves_int64int6433float3d.cpp
  ${CMAKE_CURRENT_LIST_DIR}/embedded_intersection_curves_intint33double3d.cpp
  ${CMAKE_CURRENT_LIST_DIR}/embedded_intersection_curves_intint33float3d.cpp
  ${CMAKE_CURRENT_LIST_DIR}/embedded_intersection_curves_intint6433double3d.cpp
  ${CMAKE_CURRENT_LIST_DIR}/embedded_intersection_curves_intint6433float3d.cpp
  ${CMAKE_CURRENT_LIST_DIR}/embedded_self_intersection_curves.cpp
  ${CMAKE_CURRENT_LIST_DIR}/embedded_self_intersection_curves_int3double3d.cpp
  ${CMAKE_CURRENT_LIST_DIR}/embedded_self_intersection_curves_int3float3d.cpp
  ${CMAKE_CURRENT_LIST_DIR}/embedded_self_intersection_curves_int643double3d.cpp
  ${CMAKE_CURRENT_LIST_DIR}/embedded_self_intersection_curves_int643float3d.cpp
  ${CMAKE_CURRENT_LIST_DIR}/isobands.cpp
  ${CMAKE_CURRENT_LIST_DIR}/mesh_arrangement.cpp
  ${CMAKE_CURRENT_LIST_DIR}/mesh_arrangement_int3double3d.cpp
  ${CMAKE_CURRENT_LIST_DIR}/mesh_arrangement_int3float3d.cpp
  ${CMAKE_CURRENT_LIST_DIR}/mesh_arrangement_int643double3d.cpp
  ${CMAKE_CURRENT_LIST_DIR}/mesh_arrangement_int643float3d.cpp
  ${CMAKE_CURRENT_LIST_DIR}/mesh_arrangement_intdynfloat3d.cpp
  ${CMAKE_CURRENT_LIST_DIR}/mesh_arrangement_intdyndouble3d.cpp
  ${CMAKE_CURRENT_LIST_DIR}/mesh_arrangement_int64dynfloat3d.cpp
  ${CMAKE_CURRENT_LIST_DIR}/mesh_arrangement_int64dyndouble3d.cpp
  ${CMAKE_CURRENT_LIST_DIR}/polygon_arrangement.cpp
  ${CMAKE_CURRENT_LIST_DIR}/polygon_arrangement_int3double3d.cpp
  ${CMAKE_CURRENT_LIST_DIR}/polygon_arrangement_int3float3d.cpp
  ${CMAKE_CURRENT_LIST_DIR}/polygon_arrangement_int643double3d.cpp
  ${CMAKE_CURRENT_LIST_DIR}/polygon_arrangement_int643float3d.cpp
)
