/*
 * Copyright (c) 2025 XLAB
 * All rights reserved.
 *
 * This file is part of trueform (trueform.polydera.com)
 *
 * Licensed for noncommercial use under the PolyForm Noncommercial
 * License 1.0.0.
 * Commercial licensing available via info@polydera.com.
 *
 * Author: Žiga Sajovic
 */

// The WASM glue JS is generated by Emscripten and shipped alongside the
// built bundle; it has no TypeScript declarations of its own. The embind
// surface is intentionally untyped at this boundary — `native()` returns
// a loosely-typed handle that the higher-level wrappers consume.

declare const createModule: () => Promise<any>;
export default createModule;
