/*
 * Copyright (c) 2025 XLAB
 * All rights reserved.
 *
 * This file is part of trueform (trueform.polydera.com)
 *
 * Licensed for noncommercial use under the PolyForm Noncommercial
 * License 1.0.0.
 * Commercial licensing available via info@polydera.com.
 *
 * Author: Žiga Sajovic
 */
#pragma once
#include "../../core/algorithm/parallel_for_each.hpp"
#include "../../core/blocked_buffer.hpp"
#include "../../core/buffer.hpp"
#include "../../core/point.hpp"
#include "../../core/points_buffer.hpp"
#include "../../core/polygons_buffer.hpp"
#include "../../core/views/sequence_range.hpp"
#include "../volume.hpp"
#include "./field_value.hpp"
#include "./flying_edges_tables.hpp"
#include "./isosurface_classify.hpp"
#include <array>
#include <cstdint>

namespace tf {
namespace volume_detail {

// Flying Edges 3D (Schroeder, Maynard, Geveci 2015).
//
// A four-pass, row-parallel isocontouring algorithm. It classifies the volume
// one x-row at a time, reuses those classifications to size the output exactly,
// prefix-sums per-row offsets, then generates the welded indexed mesh directly
// — no triangle soup and no post-hoc vertex weld. Each intersection point is
// produced exactly once by the cell that "owns" its edge, so the surface is
// watertight by construction.
//
// This is a general port: no SIMD, no gradients/normals, no subvolume
// stitching. It produces the same surface, orientation and welded output shape
// as `marching_cubes`, and is the implementation behind the stable
// `tf::make_isosurface` entry point.
//
// The three O(voxels) passes (classify, count, generate) run in parallel over
// z-slices; only the O(rows) prefix sum is serial. This is safe because each
// slice writes a disjoint set of x-case rows, per-row metadata, and output
// point/triangle id ranges — the sole cross-slice writes are the +z boundary
// edge counts, which a single slice (z = nz-2) contributes to the final grid
// plane (z = nz-1). This row/slice independence is exactly what makes Flying
// Edges scale where marching cubes' shared triangle soup does not.
//
// Edge/corner numbering follows the Flying Edges convention (distinct from the
// Bourke marching-cubes numbering used elsewhere in this module):
//   - corner i has offset (i&1, (i>>1)&1, (i>>2)&1)
//   - a cell owns edges 0 (x, at y0z0), 4 (y, at x0z0), 8 (z, at x0y0); the
//     other nine edges are owned by neighbours and only generated by a cell on
//     the volume's +x/+y/+z outer boundary.

// Boundary location code: two bits per axis, 0 interior / 1 min / 2 max, packed
// as x | (y << 2) | (z << 4). Only the max bits contribute extra boundary edges.
constexpr unsigned char fe_interior = 0;
constexpr unsigned char fe_min = 1;
constexpr unsigned char fe_max = 2;

// Attribute the extra y/z boundary-edge points of an outer-face cell to the row
// that owns them (mirrors the counting done during generation). `meta` are the
// four cell-row meta pointers {(y,z), (y+1,z), (y,z+1), (y+1,z+1)}.
inline void fe_count_boundary(unsigned char loc, const unsigned char *uses,
                              std::int64_t *meta[4]) {
  switch (loc) {
  case 2: // x-max
    meta[0][1] += uses[5];
    meta[0][2] += uses[9];
    break;
  case 8: // y-max
    meta[1][2] += uses[10];
    break;
  case 10: // x-max + y-max
    meta[0][1] += uses[5];
    meta[0][2] += uses[9];
    meta[1][2] += uses[10];
    meta[1][2] += uses[11];
    break;
  case 32: // z-max
    meta[2][1] += uses[6];
    break;
  case 34: // x-max + z-max
    meta[0][1] += uses[5];
    meta[0][2] += uses[9];
    meta[2][1] += uses[6];
    meta[2][1] += uses[7];
    break;
  case 40: // y-max + z-max
    meta[2][1] += uses[6];
    meta[1][2] += uses[10];
    break;
  case 42: // x-max + y-max + z-max
    meta[0][1] += uses[5];
    meta[0][2] += uses[9];
    meta[1][2] += uses[10];
    meta[1][2] += uses[11];
    meta[2][1] += uses[6];
    meta[2][1] += uses[7];
    break;
  default:
    break;
  }
}

/// @brief Flying Edges isosurface. See file header. A corner is inside when
/// `sample < iso`, matching `marching_cubes` (outward winding for an SDF).
template <typename Index = int, typename Real, typename Policy>
auto flying_edges(const tf::volume<Policy> &vol, Real iso)
    -> tf::polygons_buffer<Index, Real, 3, 3> {
  const auto &dims = vol.dims();
  const int nx = dims[0], ny = dims[1], nz = dims[2];
  if (nx < 2 || ny < 2 || nz < 2)
    return {};

  const fe_tables_t &tab = fe_tables();
  using id_t = std::int64_t;
  const int xedges = nx - 1;
  const std::size_t nrows = static_cast<std::size_t>(ny) * nz;

  tf::buffer<unsigned char> xcase;
  xcase.allocate(static_cast<std::size_t>(xedges) * nrows);
  tf::buffer<id_t> meta;
  meta.allocate(6 * nrows);
  tf::buffer<int> xmin;
  xmin.allocate(nrows);
  tf::buffer<int> xmax;
  xmax.allocate(nrows);

  const auto row_index = [&](int y, int z) {
    return static_cast<std::size_t>(z) * ny + y;
  };
  const auto xcase_row = [&](int y, int z) {
    return &xcase[row_index(y, z) * xedges];
  };
  const auto meta_row = [&](int y, int z) {
    return &meta[row_index(y, z) * 6];
  };
  // The passes write case bytes and point/triangle ids through pointers that
  // may alias the volume's own storage, so reading a sample through `vol`
  // reloads its base and dimensions on every store. Hoist them once, the grid
  // into the type the call decides and emits in.
  const auto samples = vol.begin();
  Real origin[3], spacing[3];
  for (int d = 0; d < 3; ++d) {
    origin[d] = static_cast<Real>(vol.origin()[d]);
    spacing[d] = static_cast<Real>(vol.spacing()[d]);
  }
  const auto sample_row = [&](int y, int z) {
    return samples + row_index(y, z) * nx;
  };

  // pass 1: the shared x-edge classification
  classify_x_edges(vol, iso, xcase.data(), meta.data(), 6, xmin.data(),
                   xmax.data());

  // pass 2: per interior cell-row, count triangles + y/z edge points
  tf::parallel_for_each(tf::make_sequence_range(0, nz - 1), [&](int z) {
    for (int y = 0; y < ny - 1; ++y) {
      const unsigned char *X0 = xcase_row(y, z);
      const unsigned char *X1 = xcase_row(y + 1, z);
      const unsigned char *X2 = xcase_row(y, z + 1);
      const unsigned char *X3 = xcase_row(y + 1, z + 1);
      id_t *M0 = meta_row(y, z);
      id_t *m[4] = {M0, meta_row(y + 1, z), meta_row(y, z + 1),
                    meta_row(y + 1, z + 1)};
      const std::size_t r0 = row_index(y, z), r1 = row_index(y + 1, z),
                        r2 = row_index(y, z + 1), r3 = row_index(y + 1, z + 1);

      bool x_ints = true;
      if ((M0[0] | m[1][0] | m[2][0] | m[3][0]) == 0) {
        if (X0[0] == X1[0] && X1[0] == X2[0] && X2[0] == X3[0]) {
          M0[4] = 0;
          M0[5] = 0;
          continue; // all 8 corners same sign — no surface in this cell-row
        }
        x_ints = false; // no x crossings but y/z edges may still cross
      }

      int x_left = 0, x_right = nx - 1;
      if (x_ints) {
        x_left = std::min(std::min(xmin[r0], xmin[r1]),
                          std::min(xmin[r2], xmin[r3]));
        x_right = std::max(std::max(xmax[r0], xmax[r1]),
                           std::max(xmax[r2], xmax[r3]));
        // A surface can still cross a y/z edge just outside the x trim; widen
        // when the four rows disagree on the inside bit at the trim boundary.
        if (x_left > 0) {
          if ((X0[x_left] & 0x1u) != (X1[x_left] & 0x1u) ||
              (X1[x_left] & 0x1u) != (X2[x_left] & 0x1u) ||
              (X2[x_left] & 0x1u) != (X3[x_left] & 0x1u))
            x_left = 0;
        }
        if (x_right < nx - 1) {
          if ((X0[x_right] & 0x2u) != (X1[x_right] & 0x2u) ||
              (X1[x_right] & 0x2u) != (X2[x_right] & 0x2u) ||
              (X2[x_right] & 0x2u) != (X3[x_right] & 0x2u))
            x_right = nx - 1;
        }
      }
      M0[4] = x_left;
      M0[5] = x_right;

      const unsigned char y_loc = (y >= ny - 2) ? fe_max : fe_interior;
      const unsigned char z_loc = (z >= nz - 2) ? fe_max : fe_interior;
      const unsigned char yz_loc =
          static_cast<unsigned char>((y_loc << 2) | (z_loc << 4));

      for (int x = x_left; x < x_right; ++x) {
        const unsigned char c = static_cast<unsigned char>(
            X0[x] | (X1[x] << 2) | (X2[x] << 4) | (X3[x] << 6));
        const unsigned char tri_count = tab.edge_cases[c][0];
        if (tri_count == 0)
          continue;
        M0[3] += tri_count;
        const unsigned char *uses = tab.edge_uses[c].data();
        M0[1] += uses[4];
        M0[2] += uses[8];
        const unsigned char loc = static_cast<unsigned char>(
            yz_loc | ((x >= nx - 2) ? fe_max : fe_interior));
        if (loc != fe_interior)
          fe_count_boundary(loc, uses, m);
      }
    }
  });

  // pass 3: prefix-sum per-row counts into starting point/triangle ids
  id_t x_pts = 0, y_pts = 0, z_pts = 0, tri_total = 0;
  for (int z = 0; z < nz; ++z)
    for (int y = 0; y < ny; ++y) {
      id_t *m = meta_row(y, z);
      const id_t xc = m[0], yc = m[1], zc = m[2], tc = m[3];
      m[0] = x_pts + y_pts + z_pts; // start id for this row's x-edge points
      m[1] = m[0] + xc;             // then y-edge points
      m[2] = m[1] + yc;             // then z-edge points
      m[3] = tri_total;             // start triangle id
      x_pts += xc;
      y_pts += yc;
      z_pts += zc;
      tri_total += tc;
    }

  const id_t point_count = x_pts + y_pts + z_pts;
  const id_t triangle_count = tri_total;
  if (triangle_count == 0)
    return {};

  tf::buffer<Real> points;
  points.allocate(static_cast<std::size_t>(point_count) * 3);
  tf::buffer<Index> tris;
  tris.allocate(static_cast<std::size_t>(triangle_count) * 3);
  Real *const point_data = points.data();
  Index *const tri_data = tris.data();

  // Interpolate the crossing on FE `edge` of cell (cx, cy, cz) into point `pid`.
  // Unified for owned and boundary edges via the edge's corner geometry.
  const auto interpolate = [&](int cx, int cy, int cz, int edge, id_t pid) {
    const auto &oa = fe_corner_offset[fe_edge_corner[edge][0]];
    const auto &ob = fe_corner_offset[fe_edge_corner[edge][1]];
    const int a[3] = {cx + oa[0], cy + oa[1], cz + oa[2]};
    const int b[3] = {cx + ob[0], cy + ob[1], cz + ob[2]};
    const Real va = field_value<Real>(sample_row(a[1], a[2])[a[0]]);
    const Real vb = field_value<Real>(sample_row(b[1], b[2])[b[0]]);
    const Real denom = vb - va;
    const Real t = (denom != Real{0}) ? (iso - va) / denom : Real{0.5};
    Real *p = point_data + static_cast<std::size_t>(pid) * 3;
    for (int d = 0; d < 3; ++d) {
      const Real pa = origin[d] + static_cast<Real>(a[d]) * spacing[d];
      const Real pb = origin[d] + static_cast<Real>(b[d]) * spacing[d];
      p[d] = pa + (pb - pa) * t;
    }
  };

  // pass 4: generate points and triangles per cell-row
  tf::parallel_for_each(tf::make_sequence_range(0, nz - 1), [&](int z) {
    for (int y = 0; y < ny - 1; ++y) {
      const id_t *M0 = meta_row(y, z);
      const id_t *M1 = meta_row(y + 1, z);
      const id_t *M2 = meta_row(y, z + 1);
      const id_t *M3 = meta_row(y + 1, z + 1);
      if (M0[3] == M1[3])
        continue; // no triangles start in this cell-row

      const int x_left = static_cast<int>(M0[4]);
      const int x_right = static_cast<int>(M0[5]);
      const unsigned char *X0 = xcase_row(y, z);
      const unsigned char *X1 = xcase_row(y + 1, z);
      const unsigned char *X2 = xcase_row(y, z + 1);
      const unsigned char *X3 = xcase_row(y + 1, z + 1);

      id_t eid[12];
      {
        const unsigned char c0 = static_cast<unsigned char>(
            X0[x_left] | (X1[x_left] << 2) | (X2[x_left] << 4) |
            (X3[x_left] << 6));
        const unsigned char *u = tab.edge_uses[c0].data();
        eid[0] = M0[0];
        eid[1] = M1[0];
        eid[2] = M2[0];
        eid[3] = M3[0];
        eid[4] = M0[1];
        eid[5] = eid[4] + u[4];
        eid[6] = M2[1];
        eid[7] = eid[6] + u[6];
        eid[8] = M0[2];
        eid[9] = eid[8] + u[8];
        eid[10] = M1[2];
        eid[11] = eid[10] + u[10];
      }

      id_t tri_id = M0[3];
      const unsigned char y_loc =
          (y < 1) ? fe_min : ((y >= ny - 2) ? fe_max : fe_interior);
      const unsigned char z_loc =
          (z < 1) ? fe_min : ((z >= nz - 2) ? fe_max : fe_interior);
      const unsigned char yz_loc =
          static_cast<unsigned char>((y_loc << 2) | (z_loc << 4));

      for (int x = x_left; x < x_right; ++x) {
        const unsigned char c = static_cast<unsigned char>(
            X0[x] | (X1[x] << 2) | (X2[x] << 4) | (X3[x] << 6));
        const auto &ec = tab.edge_cases[c];
        const unsigned char tri_count = ec[0];
        if (tri_count == 0)
          continue;

        for (int ti = 0, ei = 1; ti < tri_count; ++ti, ei += 3) {
          const id_t tid = tri_id++;
          Index *tri = tri_data + static_cast<std::size_t>(tid) * 3;
          tri[0] = static_cast<Index>(eid[ec[ei]]);
          tri[1] = static_cast<Index>(eid[ec[ei + 1]]);
          tri[2] = static_cast<Index>(eid[ec[ei + 2]]);
        }

        const unsigned char *u = tab.edge_uses[c].data();
        const unsigned char loc = static_cast<unsigned char>(
            yz_loc | ((x < 1) ? fe_min : ((x >= nx - 2) ? fe_max : fe_interior)));
        if (tab.includes_axes[c] || loc != fe_interior) {
          if (u[0])
            interpolate(x, y, z, 0, eid[0]);
          if (u[4])
            interpolate(x, y, z, 4, eid[4]);
          if (u[8])
            interpolate(x, y, z, 8, eid[8]);
          const bool xb = (loc & 0x2u) != 0;
          const bool yb = (loc & 0x8u) != 0;
          const bool zb = (loc & 0x20u) != 0;
          if (xb) {
            if (u[5])
              interpolate(x, y, z, 5, eid[5]);
            if (u[9])
              interpolate(x, y, z, 9, eid[9]);
          }
          if (yb) {
            if (u[1])
              interpolate(x, y, z, 1, eid[1]);
            if (u[10])
              interpolate(x, y, z, 10, eid[10]);
          }
          if (zb) {
            if (u[2])
              interpolate(x, y, z, 2, eid[2]);
            if (u[6])
              interpolate(x, y, z, 6, eid[6]);
          }
          if (xb && yb && u[11])
            interpolate(x, y, z, 11, eid[11]);
          if (xb && zb && u[7])
            interpolate(x, y, z, 7, eid[7]);
          if (yb && zb && u[3])
            interpolate(x, y, z, 3, eid[3]);
        }

        // Advance owned edge ids; recompute the boundary-paired ids.
        eid[0] += u[0];
        eid[1] += u[1];
        eid[2] += u[2];
        eid[3] += u[3];
        eid[4] += u[4];
        eid[5] = eid[4] + u[5];
        eid[6] += u[6];
        eid[7] = eid[6] + u[7];
        eid[8] += u[8];
        eid[9] = eid[8] + u[9];
        eid[10] += u[10];
        eid[11] = eid[10] + u[11];
      }
    }
  });

  tf::polygons_buffer<Index, Real, 3, 3> result;
  result.points_buffer() = tf::points_buffer<Real, 3>(std::move(points));
  result.faces_buffer() = tf::blocked_buffer<Index, 3>(std::move(tris));
  return result;
}

} // namespace volume_detail
} // namespace tf
