/*
 * Copyright (c) 2025 XLAB
 * All rights reserved.
 *
 * This file is part of trueform (trueform.polydera.com)
 *
 * Licensed for noncommercial use under the PolyForm Noncommercial
 * License 1.0.0.
 * Commercial licensing available via info@polydera.com.
 *
 * Author: Žiga Sajovic
 */
#pragma once
#include "../../core/algorithm/parallel_copy.hpp"
#include "../../core/algorithm/parallel_for_each.hpp"
#include "../../core/algorithm/parallel_transform.hpp"
#include "../../core/buffer.hpp"
#include "../../core/points_buffer.hpp"
#include "../../core/views/drop.hpp"
#include "../../core/views/sequence_range.hpp"
#include "../volume.hpp"
#include "./field_value.hpp"
#include <algorithm>
#include <array>
#include <cstddef>
#include <cstdint>

namespace tf {
namespace volume_detail {

// Flying Edges 2D (Schroeder, Maynard, Geveci 2015) — isoline extraction.
//
// A four-pass, row-parallel isocontouring algorithm for a regular 2D grid, the
// planar sibling of the 3D `flying_edges` in this module (and a port of VTK's
// vtkFlyingEdges2D). Pass 1 classifies the x-edges of every grid row and
// records per-row crossing counts and trim bounds. Pass 2 walks each cell row
// (a row of pixels), combines the two bounding x-edge case values into the
// marching-squares case, and counts the y-edge crossings and output segments.
// A serial prefix sum then converts the per-row counts into starting point and
// segment ids, sizing the output exactly. Pass 4 generates the points and
// segments into the pre-allocated arrays. Each intersection point is produced
// exactly once by the cell that owns its edge.
//
// Passes 1, 2 and 4 run in parallel over rows; only the O(rows) prefix sum is
// serial. Each row writes a disjoint set of x-cases, per-row metadata and
// output id ranges, so the passes are race free.
//
// Edge/vertex numbering follows the VTK Flying Edges 2D convention:
//   - vertex i of a pixel has offset (i & 1, i >> 1)
//   - edge 0 = bottom x-edge (v0-v1), edge 1 = top x-edge (v2-v3),
//     edge 2 = left y-edge (v0-v2), edge 3 = right y-edge (v1-v3)
//   - a cell owns edges 0 and 2; edges 1 and 3 are owned by the +y / +x
//     neighbours and are only generated by cells on the grid's outer boundary.
//
// Case numbering also follows VTK: bit i is set when vertex i is at or above
// the isovalue (`sample >= iso`), assembled as `bottom_case | (top_case << 2)`
// from the two bounding x-edge cases.

// The offsets of each vertex (in index space) from the pixel origin.
inline constexpr std::array<std::array<int, 2>, 4> fe2d_vert_offset = {{
    {0, 0},
    {1, 0},
    {0, 1},
    {1, 1},
}};

// The two vertices bounding each of the four pixel edges.
inline constexpr std::array<std::array<int, 2>, 4> fe2d_edge_vert = {{
    {0, 1},
    {2, 3},
    {0, 2},
    {1, 3},
}};

// Per-case output tables in FE 2D edge numbering. `edge_cases` is the
// marching-squares case table straight from VTK: [segment_count, (e0,e1),
// (e2,e3)]. `edge_uses` and `includes_axes` are cheap acceleration structures
// derived from it, mirroring the 3D `fe_tables_t`.
struct fe2d_tables_t {
  std::array<std::array<unsigned char, 5>, 16> edge_cases{};
  std::array<std::array<unsigned char, 4>, 16> edge_uses{};
  std::array<unsigned char, 16> includes_axes{};
};

inline auto build_fe2d_tables() -> fe2d_tables_t {
  fe2d_tables_t tab;
  // Format for each case: segment count, (id0, id1), (id2, id3).
  tab.edge_cases = {{
      {0, 0, 0, 0, 0}, // case 0
      {1, 0, 2, 0, 0}, // 1
      {1, 3, 0, 0, 0}, // 2
      {1, 3, 2, 0, 0}, // 3
      {1, 2, 1, 0, 0}, // 4
      {1, 0, 1, 0, 0}, // 5
      {2, 2, 1, 3, 0}, // 6
      {1, 3, 1, 0, 0}, // 7
      {1, 1, 3, 0, 0}, // 8
      {2, 0, 2, 3, 1}, // 9
      {1, 1, 0, 0, 0}, // 10
      {1, 1, 2, 0, 0}, // 11
      {1, 2, 3, 0, 0}, // 12
      {1, 0, 3, 0, 0}, // 13
      {1, 2, 0, 0, 0}, // 14
      {0, 0, 0, 0, 0}, // 15
  }};

  for (int c = 0; c < 16; ++c) {
    const auto &ec = tab.edge_cases[c];
    const int count = ec[0];
    auto &uses = tab.edge_uses[c];
    for (int i = 0; i < count * 2; ++i)
      uses[ec[1 + i]] = 1;
    tab.includes_axes[c] = static_cast<unsigned char>(uses[0] | uses[2]);
  }
  return tab;
}

inline const fe2d_tables_t &fe2d_tables() {
  static const fe2d_tables_t tables = build_fe2d_tables();
  return tables;
}

// Boundary location code, as in VTK: two bits per axis, 0 interior / 1 min /
// 2 max, packed as x | (y << 2). Only the max bits contribute extra points.
constexpr unsigned char fe2d_interior = 0;
constexpr unsigned char fe2d_min = 1;
constexpr unsigned char fe2d_max = 2;

/// @brief Flying Edges 2D isocontouring. See file header.
///
/// Extracts the isoline `{ p : field(p) == iso }` of the grid's bilinear
/// field, one isovalue per invocation. Each edge crossing is generated exactly
/// once, so the product is a WELDED point set plus the index pairs that name
/// the segments over it — which is what makes joining them into polylines a
/// topological step downstream rather than a coordinate search. Points are in
/// the grid's own 2D frame (`origin + (index + t) * spacing`); both outputs are
/// appended, the segments rebased onto this call's block of points, so repeated
/// invocations (e.g. one per isovalue) accumulate.
///
/// Degenerate (zero-length) segments can be produced when the isovalue hits
/// grid samples exactly, matching the VTK reference implementation.
template <typename Index, typename RealType, typename Policy>
auto flying_edges_2d(const tf::volume<Policy> &grid, RealType iso,
                     tf::points_buffer<RealType, 2> &contour_points,
                     tf::buffer<Index> &contour_segments) -> void {
  const int nx = grid.dims()[0], ny = grid.dims()[1];
  if (nx < 2 || ny < 2)
    return;

  const fe2d_tables_t &tab = fe2d_tables();
  using id_t = std::int64_t;
  const int xedges = nx - 1;
  const auto samples = make_field_samples<RealType>(grid);
  RealType origin[2], spacing[2];
  for (int d = 0; d < 2; ++d) {
    origin[d] = static_cast<RealType>(grid.origin()[d]);
    spacing[d] = static_cast<RealType>(grid.spacing()[d]);
  }

  // Per-cell x-edge case values, one row of x-edges per grid row.
  tf::buffer<unsigned char> xcase;
  xcase.allocate(static_cast<std::size_t>(xedges) * ny);
  // Per-row metadata: [0] x-crossings -> x-point start id, [1] y-crossings ->
  // y-point start id, [2] segment count -> segment start id, [3]/[4] final
  // trim bounds (written in pass 2, read in pass 4).
  tf::buffer<id_t> meta;
  meta.allocate(5 * static_cast<std::size_t>(ny));
  // Pass-1 trim bounds per row, kept separate from `meta` so pass 2 can read
  // its neighbour row's bounds without racing pass 2's own writes.
  tf::buffer<int> xmin;
  xmin.allocate(ny);
  tf::buffer<int> xmax;
  xmax.allocate(ny);

  const auto xcase_row = [&](int y) {
    return &xcase[static_cast<std::size_t>(y) * xedges];
  };
  const auto meta_row = [&](int y) {
    return &meta[static_cast<std::size_t>(y) * 5];
  };

  // Pass 1: classify x-edges per row, count crossings, find trim bounds
  tf::parallel_for_each(tf::make_sequence_range(0, ny), [&](int y) {
    const auto row_ptr = samples + static_cast<std::ptrdiff_t>(y) * nx;
    unsigned char *xc = xcase_row(y);
    id_t *m = meta_row(y);
    m[0] = m[1] = m[2] = m[3] = m[4] = 0;
    int xl = xedges; // no crossing sentinel (xl > xr)
    int xr = 0;
    id_t crossings = 0;
    RealType s1 = row_ptr[0];
    for (int x = 0; x < xedges; ++x) {
      const RealType s0 = s1;
      s1 = row_ptr[x + 1];
      // VTK convention: bit set when the vertex is at or above the isovalue.
      const unsigned char cs = static_cast<unsigned char>(
          (s0 < iso ? 0 : 1) | (s1 < iso ? 0 : 2));
      xc[x] = cs;
      if (cs == 1 || cs == 2) {
        ++crossings;
        if (x < xl)
          xl = x;
        xr = x + 1;
      }
    }
    m[0] = crossings;
    xmin[y] = xl;
    xmax[y] = xr;
  });

  // Pass 2: per cell row, count segments and y-edge crossings
  tf::parallel_for_each(tf::make_sequence_range(0, ny - 1), [&](int y) {
    const unsigned char *X0 = xcase_row(y);
    const unsigned char *X1 = xcase_row(y + 1);
    id_t *M0 = meta_row(y);
    const id_t *M1 = meta_row(y + 1);

    // Determine whether this row of cells needs processing. If there are no
    // x-edge crossings and no y-edge crossing anywhere (with zero x crossings
    // each row's cases are constant, so comparing the first suffices), the
    // row is contour free.
    bool x_ints = true;
    if ((M0[0] | M1[0]) == 0) {
      if (X0[0] == X1[0])
        return;
      x_ints = false; // there are y-edge crossings, however
    }

    // The trim bounds may need adjustment if the contour travels between the
    // two bounding rows of x-edges (without crossing the x-edges themselves).
    int x_left = std::min(xmin[y], xmin[y + 1]);
    int x_right = std::max(xmax[y], xmax[y + 1]);
    if (x_ints) {
      if (x_left > 0) {
        if ((X0[x_left] & 0x1u) != (X1[x_left] & 0x1u))
          x_left = 0;
      }
      if (x_right < nx - 1) {
        if ((X0[x_right] & 0x2u) != (X1[x_right] & 0x2u))
          x_right = nx - 1;
      }
    } else {
      x_left = 0;
      x_right = nx - 1;
    }
    M0[3] = x_left;
    M0[4] = x_right;

    const unsigned char y_loc = static_cast<unsigned char>(
        ((y >= ny - 2) ? fe2d_max : fe2d_interior) << 2);

    // Run along the trimmed cells, counting segments and y-edge crossings.
    for (int x = x_left; x < x_right; ++x) {
      const unsigned char c =
          static_cast<unsigned char>(X0[x] | (X1[x] << 2));
      const unsigned char seg_count = tab.edge_cases[c][0];
      if (seg_count == 0)
        continue;
      M0[2] += seg_count;
      const unsigned char *uses = tab.edge_uses[c].data();
      M0[1] += uses[2]; // owned (left) y-edge always counted
      const unsigned char loc = static_cast<unsigned char>(
          y_loc | ((x >= nx - 2) ? fe2d_max : fe2d_interior));
      if (loc & 0x2u) // +x boundary: the right y-edge has no owner cell
        M0[1] += uses[3];
    }
  });

  // Pass 3: prefix-sum per-row counts into starting point/segment ids
  id_t x_pts = 0, y_pts = 0, seg_total = 0;
  for (int y = 0; y < ny; ++y) {
    id_t *m = meta_row(y);
    const id_t xc = m[0], yc = m[1], sc = m[2];
    m[0] = x_pts + y_pts; // start id for this row's x-edge points
    m[1] = m[0] + xc;     // then y-edge points
    m[2] = seg_total;     // start segment id
    x_pts += xc;
    y_pts += yc;
    seg_total += sc;
  }

  const id_t point_count = x_pts + y_pts;
  const id_t segment_count = seg_total;
  if (segment_count == 0)
    return;

  // Welded intermediate output: each edge crossing is generated exactly once.
  tf::buffer<RealType> points;
  points.allocate(static_cast<std::size_t>(point_count) * 2);
  tf::buffer<id_t> segments;
  segments.allocate(static_cast<std::size_t>(segment_count) * 2);

  // Interpolate the crossing on FE edge `edge` of cell (cx, cy) into point
  // `pid`, baking the grid origin/spacing into the coordinates directly.
  const auto interpolate = [&](int cx, int cy, int edge, id_t pid) {
    const auto &oa = fe2d_vert_offset[fe2d_edge_vert[edge][0]];
    const auto &ob = fe2d_vert_offset[fe2d_edge_vert[edge][1]];
    const int ax = cx + oa[0], ay = cy + oa[1];
    const int bx = cx + ob[0], by = cy + ob[1];
    const RealType va = samples[ax + static_cast<std::ptrdiff_t>(ay) * nx];
    const RealType vb = samples[bx + static_cast<std::ptrdiff_t>(by) * nx];
    const RealType denom = vb - va;
    const RealType t =
        (denom != RealType{0}) ? (iso - va) / denom : RealType{0.5};
    RealType *p = &points[static_cast<std::size_t>(pid) * 2];
    p[0] = origin[0] +
           (static_cast<RealType>(ax) + t * static_cast<RealType>(bx - ax)) *
               spacing[0];
    p[1] = origin[1] +
           (static_cast<RealType>(ay) + t * static_cast<RealType>(by - ay)) *
               spacing[1];
  };

  // Pass 4: generate points and segments per cell row
  tf::parallel_for_each(tf::make_sequence_range(0, ny - 1), [&](int y) {
    const id_t *M0 = meta_row(y);
    const id_t *M1 = meta_row(y + 1);
    if (M0[2] == M1[2])
      return; // no segments start in this cell row

    const int x_left = static_cast<int>(M0[3]);
    const int x_right = static_cast<int>(M0[4]);
    const unsigned char *X0 = xcase_row(y);
    const unsigned char *X1 = xcase_row(y + 1);

    // Set up the point ids on the pixel edges at the left trim cell.
    id_t eid[4];
    {
      const unsigned char c0 =
          static_cast<unsigned char>(X0[x_left] | (X1[x_left] << 2));
      const unsigned char *u = tab.edge_uses[c0].data();
      eid[0] = M0[0]; // bottom x-edge
      eid[1] = M1[0]; // top x-edge
      eid[2] = M0[1]; // left y-edge
      eid[3] = eid[2] + u[2];
    }

    id_t seg_id = M0[2];
    const unsigned char y_loc = static_cast<unsigned char>(
        (((y < 1) ? fe2d_min : fe2d_interior) |
         ((y >= ny - 2) ? fe2d_max : fe2d_interior))
        << 2);

    for (int x = x_left; x < x_right; ++x) {
      const unsigned char c =
          static_cast<unsigned char>(X0[x] | (X1[x] << 2));
      const auto &ec = tab.edge_cases[c];
      const unsigned char seg_count = ec[0];
      const unsigned char *u = tab.edge_uses[c].data();
      if (seg_count != 0) {
        // Generate the segments for this case.
        for (int si = 0, ei = 1; si < seg_count; ++si, ei += 2) {
          id_t *seg = &segments[static_cast<std::size_t>(seg_id++) * 2];
          seg[0] = eid[ec[ei]];
          seg[1] = eid[ec[ei + 1]];
        }

        // Generate the point(s) on the pixel axes, taking the boundary into
        // account: cells on the +x/+y boundary also own their right/top edge.
        const unsigned char loc = static_cast<unsigned char>(
            y_loc | ((x < 1) ? fe2d_min : fe2d_interior) |
            ((x >= nx - 2) ? fe2d_max : fe2d_interior));
        if (tab.includes_axes[c] || loc != fe2d_interior) {
          if (u[0])
            interpolate(x, y, 0, eid[0]);
          if (u[2])
            interpolate(x, y, 2, eid[2]);
          switch (loc) {
          case 2: // +x
          case 3:
          case 6:
          case 7:
            if (u[3])
              interpolate(x, y, 3, eid[3]);
            break;
          case 8: // +y
          case 9:
          case 12:
          case 13:
            if (u[1])
              interpolate(x, y, 1, eid[1]);
            break;
          case 10: // +x +y
          case 11:
          case 14:
          case 15:
            if (u[1])
              interpolate(x, y, 1, eid[1]);
            if (u[3])
              interpolate(x, y, 3, eid[3]);
            break;
          default: // interior, or -x/-y boundaries
            break;
          }
        }
      }

      // Advance the edge point ids along the row (no-op for empty cases).
      eid[0] += u[0];
      eid[1] += u[1];
      eid[2] += u[2];
      eid[3] = eid[2] + u[3];
    }
  });

  // Append the welded product, rebasing the segments onto its points
  const auto point_base = static_cast<id_t>(contour_points.size());
  const auto coordinates_held = contour_points.data_buffer().size();
  contour_points.reallocate(static_cast<std::size_t>(point_base) +
                            static_cast<std::size_t>(point_count));
  tf::parallel_copy(points,
                    tf::drop(contour_points.data_buffer(), coordinates_held));

  const auto segments_held = contour_segments.size();
  contour_segments.reallocate(segments_held +
                              static_cast<std::size_t>(segment_count) * 2);
  tf::parallel_transform(
      segments, tf::drop(contour_segments, segments_held),
      [point_base](id_t id) { return static_cast<Index>(id + point_base); });
}

} // namespace volume_detail
} // namespace tf
