/*
 * Copyright (c) 2025 XLAB
 * All rights reserved.
 *
 * This file is part of trueform (trueform.polydera.com)
 *
 * Licensed for noncommercial use under the PolyForm Noncommercial
 * License 1.0.0.
 * Commercial licensing available via info@polydera.com.
 *
 * Author: Žiga Sajovic
 */
#pragma once
#include "./marching_cubes_tables.hpp"
#include <array>

namespace tf {
namespace volume_detail {

// The marching-cubes case authority in the Flying Edges numbering, which every
// extractor of this module and the dual-contouring topology stand on:
//   - corner i has offset (i&1, (i>>1)&1, (i>>2)&1)
//   - a cell owns edges 0 (x, at y0z0), 4 (y, at x0z0), 8 (z, at x0y0); the
//     other nine edges are owned by neighbours and only generated by a cell on
//     the volume's +x/+y/+z outer boundary.
// It is derived once from the module's Bourke tables, so the surface and the
// winding are identical to `marching_cubes` by construction.

inline constexpr std::array<std::array<int, 3>, 8> fe_corner_offset = {{
    {0, 0, 0}, {1, 0, 0}, {0, 1, 0}, {1, 1, 0},
    {0, 0, 1}, {1, 0, 1}, {0, 1, 1}, {1, 1, 1},
}};

inline constexpr std::array<std::array<int, 2>, 12> fe_edge_corner = {{
    {0, 1}, {2, 3}, {4, 5}, {6, 7}, {0, 2}, {1, 3},
    {4, 6}, {5, 7}, {0, 4}, {1, 5}, {2, 6}, {3, 7},
}};

// Per-case output tables, in Flying Edges edge numbering. Derived once from the
// module's Bourke marching-cubes tables so the triangulation (and therefore the
// surface and winding) is identical to `marching_cubes` by construction.
struct fe_tables_t {
  // [triangle_count, e0, e1, e2, ...] with FE edge indices.
  std::array<std::array<unsigned char, 16>, 256> edge_cases{};
  // Which of the 12 FE edges the case's triangles reference.
  std::array<std::array<unsigned char, 12>, 256> edge_uses{};
  // Non-zero when the case uses any owned axis edge (0, 4 or 8).
  std::array<unsigned char, 256> includes_axes{};
};

inline auto build_fe_tables() -> fe_tables_t {
  fe_tables_t tab;
  const auto offset_key = [](const std::array<int, 3> &o) {
    return o[0] | (o[1] << 1) | (o[2] << 2);
  };

  // Bourke edge index -> FE edge index, matched by unordered endpoint offsets.
  std::array<int, 12> bourke_to_fe{};
  for (int e = 0; e < 12; ++e) {
    const int ka = offset_key(mc_corner_offsets[mc_edge_corners[e][0]]);
    const int kb = offset_key(mc_corner_offsets[mc_edge_corners[e][1]]);
    for (int f = 0; f < 12; ++f) {
      const int kfa = offset_key(fe_corner_offset[fe_edge_corner[f][0]]);
      const int kfb = offset_key(fe_corner_offset[fe_edge_corner[f][1]]);
      if ((ka == kfa && kb == kfb) || (ka == kfb && kb == kfa)) {
        bourke_to_fe[e] = f;
        break;
      }
    }
  }

  for (int c = 0; c < 256; ++c) {
    // Bit i of the FE case index means "FE corner i is inside" (sample < iso).
    // Translate to the Bourke corner mask so the Bourke triangle table applies.
    int bourke = 0;
    for (int b = 0; b < 8; ++b) {
      const int fe_bit = offset_key(mc_corner_offsets[b]);
      if ((c >> fe_bit) & 1)
        bourke |= (1 << b);
    }

    const int *row = mc_tri_table[bourke];
    auto &ec = tab.edge_cases[c];
    unsigned char count = 0;
    int out = 1;
    for (int i = 0; row[i] != -1; i += 3) {
      ec[out++] = static_cast<unsigned char>(bourke_to_fe[row[i]]);
      ec[out++] = static_cast<unsigned char>(bourke_to_fe[row[i + 1]]);
      ec[out++] = static_cast<unsigned char>(bourke_to_fe[row[i + 2]]);
      ++count;
    }
    ec[0] = count;

    auto &uses = tab.edge_uses[c];
    for (int i = 0; i < count * 3; ++i)
      uses[ec[1 + i]] = 1;
    tab.includes_axes[c] =
        static_cast<unsigned char>(uses[0] | uses[4] | uses[8]);
  }
  return tab;
}

// Derived once at first use, not at compile time: evaluating this table in
// every translation unit costs each of them real time, and its step count is
// past what MSVC's constexpr budget allows by default.
inline auto fe_tables() -> const fe_tables_t & {
  static const fe_tables_t tables = build_fe_tables();
  return tables;
}

} // namespace volume_detail
} // namespace tf
