/*
 * Copyright (c) 2025 Žiga Sajovic, XLAB
 * Distributed under the Boost Software License, Version 1.0.
 * https://github.com/xlabmedical/trueform
 */
#pragma once

#include "./core/aabb.hpp"                      // IWYU pragma: export
#include "./core/aabb_from.hpp"                 // IWYU pragma: export
#include "./core/aabb_like.hpp"                 // IWYU pragma: export
#include "./core/aabb_metrics.hpp"              // IWYU pragma: export
#include "./core/aabb_union.hpp"                // IWYU pragma: export
#include "./core/algorithm.hpp"                 // IWYU pragma: export
#include "./core/blocked_buffer.hpp"            // IWYU pragma: export
#include "./core/buffer.hpp"                    // IWYU pragma: export
#include "./core/classify.hpp"                  // IWYU pragma: export
#include "./core/closest_metric_point.hpp"      // IWYU pragma: export
#include "./core/closest_metric_point_pair.hpp" // IWYU pragma: export
#include "./core/closest_point_on_triangle.hpp" // IWYU pragma: export
#include "./core/closest_point_parametric.hpp"  // IWYU pragma: export
#include "./core/containment.hpp"               // IWYU pragma: export
#include "./core/contains_coplanar_point.hpp"   // IWYU pragma: export
#include "./core/contains_point.hpp"            // IWYU pragma: export
#include "./core/coordinate_type.hpp"           // IWYU pragma: export
#include "./core/cross.hpp"                     // IWYU pragma: export
#include "./core/distance.hpp"                  // IWYU pragma: export
#include "./core/dot.hpp"                       // IWYU pragma: export
#include "./core/empty_aabb.hpp"                // IWYU pragma: export
#include "./core/epsilon_inverse.hpp"           // IWYU pragma: export
#include "./core/frame.hpp"                     // IWYU pragma: export
#include "./core/frame_like.hpp"                // IWYU pragma: export
#include "./core/frame_ptr.hpp"                 // IWYU pragma: export
#include "./core/intersect_status.hpp"          // IWYU pragma: export
#include "./core/intersects.hpp"                // IWYU pragma: export
#include "./core/inverted.hpp"                  // IWYU pragma: export
#include "./core/line.hpp"                      // IWYU pragma: export
#include "./core/line_like.hpp"                 // IWYU pragma: export
#include "./core/line_line_check.hpp"           // IWYU pragma: export
#include "./core/local_value.hpp"               // IWYU pragma: export
#include "./core/local_vector.hpp"              // IWYU pragma: export
#include "./core/metric_point.hpp"              // IWYU pragma: export
#include "./core/metric_point_pair.hpp"         // IWYU pragma: export
#include "./core/minimal_maximal_distance.hpp"  // IWYU pragma: export
#include "./core/normal.hpp"                    // IWYU pragma: export
#include "./core/normalize.hpp"                 // IWYU pragma: export
#include "./core/normalized.hpp"                // IWYU pragma: export
#include "./core/offset_block_buffer.hpp"       // IWYU pragma: export
#include "./core/parallelogram_area.hpp"        // IWYU pragma: export
#include "./core/plane.hpp"                     // IWYU pragma: export
#include "./core/plane_like.hpp"                // IWYU pragma: export
#include "./core/point.hpp"                     // IWYU pragma: export
#include "./core/point_like.hpp"                // IWYU pragma: export
#include "./core/point_view.hpp"                // IWYU pragma: export
#include "./core/points.hpp"                    // IWYU pragma: export
#include "./core/policy.hpp"                    // IWYU pragma: export
#include "./core/polygon.hpp"                   // IWYU pragma: export
#include "./core/polygons.hpp"                  // IWYU pragma: export
#include "./core/projector.hpp"                 // IWYU pragma: export
#include "./core/range.hpp"                     // IWYU pragma: export
#include "./core/ray.hpp"                       // IWYU pragma: export
#include "./core/ray_aabb_check.hpp"            // IWYU pragma: export
#include "./core/ray_cast.hpp"                  // IWYU pragma: export
#include "./core/ray_cast_info.hpp"             // IWYU pragma: export
#include "./core/ray_config.hpp"                // IWYU pragma: export
#include "./core/ray_hit.hpp"                   // IWYU pragma: export
#include "./core/ray_hit_info.hpp"              // IWYU pragma: export
#include "./core/ray_like.hpp"                  // IWYU pragma: export
#include "./core/segment.hpp"                   // IWYU pragma: export
#include "./core/segments.hpp"                  // IWYU pragma: export
#include "./core/sidedness.hpp"                 // IWYU pragma: export
#include "./core/small_vector.hpp"              // IWYU pragma: export
#include "./core/sphere.hpp"                    // IWYU pragma: export
#include "./core/sphere_like.hpp"               // IWYU pragma: export
#include "./core/sqrt.hpp"                      // IWYU pragma: export
#include "./core/static_size.hpp"               // IWYU pragma: export
#include "./core/tick_tock.hpp"                 // IWYU pragma: export
#include "./core/transformation.hpp"            // IWYU pragma: export
#include "./core/transformation_like.hpp"       // IWYU pragma: export
#include "./core/transformation_view.hpp"       // IWYU pragma: export
#include "./core/transformed.hpp"               // IWYU pragma: export
#include "./core/unit_vector.hpp"               // IWYU pragma: export
#include "./core/unit_vector_like.hpp"          // IWYU pragma: export
#include "./core/unit_vector_view.hpp"          // IWYU pragma: export
#include "./core/unit_vectors.hpp"              // IWYU pragma: export
#include "./core/unsafe.hpp"                    // IWYU pragma: export
#include "./core/vector.hpp"                    // IWYU pragma: export
#include "./core/vector_like.hpp"               // IWYU pragma: export
#include "./core/vector_view.hpp"               // IWYU pragma: export
#include "./core/vectors.hpp"                   // IWYU pragma: export
#include "./core/view.hpp"                      // IWYU pragma: export
#include "./core/views.hpp"                     // IWYU pragma: export
#include "./core/zip_range.hpp"                 // IWYU pragma: export
