services:
  web-example:
    build:
      context: .
      dockerfile: Dockerfile
    platform: linux/amd64
    environment:
      - ARTIFACTS_DIR=/workspace/docs/wasm-examples/build/dist
    working_dir: /workspace
    volumes:
      - ../../../:/workspace
    command: bash -lc ./docs/wasm-examples/extras/build_web.sh
