# Spatial binding sources
# Add new files here when creating new bindings
set(MODULE_SPATIAL_SOURCES
  ${CMAKE_CURRENT_LIST_DIR}/edge_mesh.cpp
  ${CMAKE_CURRENT_LIST_DIR}/edge_mesh_fp.cpp
  ${CMAKE_CURRENT_LIST_DIR}/edge_mesh_fp_int64double2d.cpp
  ${CMAKE_CURRENT_LIST_DIR}/edge_mesh_fp_int64double3d.cpp
  ${CMAKE_CURRENT_LIST_DIR}/edge_mesh_fp_int64float2d.cpp
  ${CMAKE_CURRENT_LIST_DIR}/edge_mesh_fp_int64float3d.cpp
  ${CMAKE_CURRENT_LIST_DIR}/edge_mesh_fp_intdouble2d.cpp
  ${CMAKE_CURRENT_LIST_DIR}/edge_mesh_fp_intdouble3d.cpp
  ${CMAKE_CURRENT_LIST_DIR}/edge_mesh_fp_intfloat2d.cpp
  ${CMAKE_CURRENT_LIST_DIR}/edge_mesh_fp_intfloat3d.cpp
  ${CMAKE_CURRENT_LIST_DIR}/edge_mesh_gather_ids_edge_mesh.cpp
  ${CMAKE_CURRENT_LIST_DIR}/edge_mesh_gather_ids_point_cloud.cpp
  ${CMAKE_CURRENT_LIST_DIR}/edge_mesh_intersects_edge_mesh.cpp
  ${CMAKE_CURRENT_LIST_DIR}/edge_mesh_intersects_point_cloud.cpp
  ${CMAKE_CURRENT_LIST_DIR}/edge_mesh_neighbor_search_edge_mesh.cpp
  ${CMAKE_CURRENT_LIST_DIR}/edge_mesh_neighbor_search_point_cloud.cpp
  ${CMAKE_CURRENT_LIST_DIR}/mesh.cpp
  ${CMAKE_CURRENT_LIST_DIR}/mesh_fp.cpp
  ${CMAKE_CURRENT_LIST_DIR}/mesh_fp_int3double2d.cpp
  ${CMAKE_CURRENT_LIST_DIR}/mesh_fp_int3double3d.cpp
  ${CMAKE_CURRENT_LIST_DIR}/mesh_fp_int3float2d.cpp
  ${CMAKE_CURRENT_LIST_DIR}/mesh_fp_int3float3d.cpp
  ${CMAKE_CURRENT_LIST_DIR}/mesh_fp_int643double2d.cpp
  ${CMAKE_CURRENT_LIST_DIR}/mesh_fp_int643double3d.cpp
  ${CMAKE_CURRENT_LIST_DIR}/mesh_fp_int643float2d.cpp
  ${CMAKE_CURRENT_LIST_DIR}/mesh_fp_int643float3d.cpp
  ${CMAKE_CURRENT_LIST_DIR}/mesh_fp_int64dyndouble2d.cpp
  ${CMAKE_CURRENT_LIST_DIR}/mesh_fp_int64dyndouble3d.cpp
  ${CMAKE_CURRENT_LIST_DIR}/mesh_fp_int64dynfloat2d.cpp
  ${CMAKE_CURRENT_LIST_DIR}/mesh_fp_int64dynfloat3d.cpp
  ${CMAKE_CURRENT_LIST_DIR}/mesh_fp_intdyndouble2d.cpp
  ${CMAKE_CURRENT_LIST_DIR}/mesh_fp_intdyndouble3d.cpp
  ${CMAKE_CURRENT_LIST_DIR}/mesh_fp_intdynfloat2d.cpp
  ${CMAKE_CURRENT_LIST_DIR}/mesh_fp_intdynfloat3d.cpp
  ${CMAKE_CURRENT_LIST_DIR}/mesh_gather_ids_edge_mesh.cpp
  ${CMAKE_CURRENT_LIST_DIR}/mesh_gather_ids_edge_mesh_double2d.cpp
  ${CMAKE_CURRENT_LIST_DIR}/mesh_gather_ids_edge_mesh_double3d.cpp
  ${CMAKE_CURRENT_LIST_DIR}/mesh_gather_ids_edge_mesh_float2d.cpp
  ${CMAKE_CURRENT_LIST_DIR}/mesh_gather_ids_edge_mesh_float3d.cpp
  ${CMAKE_CURRENT_LIST_DIR}/mesh_gather_ids_mesh.cpp
  ${CMAKE_CURRENT_LIST_DIR}/mesh_gather_ids_mesh_double2d.cpp
  ${CMAKE_CURRENT_LIST_DIR}/mesh_gather_ids_mesh_double3d.cpp
  ${CMAKE_CURRENT_LIST_DIR}/mesh_gather_ids_mesh_float2d.cpp
  ${CMAKE_CURRENT_LIST_DIR}/mesh_gather_ids_mesh_float3d.cpp
  ${CMAKE_CURRENT_LIST_DIR}/mesh_gather_ids_point_cloud.cpp
  ${CMAKE_CURRENT_LIST_DIR}/mesh_intersects_edge_mesh.cpp
  ${CMAKE_CURRENT_LIST_DIR}/mesh_intersects_mesh.cpp
  ${CMAKE_CURRENT_LIST_DIR}/mesh_intersects_point_cloud.cpp
  ${CMAKE_CURRENT_LIST_DIR}/mesh_neighbor_search_edge_mesh.cpp
  ${CMAKE_CURRENT_LIST_DIR}/mesh_neighbor_search_edge_mesh_double2d.cpp
  ${CMAKE_CURRENT_LIST_DIR}/mesh_neighbor_search_edge_mesh_double3d.cpp
  ${CMAKE_CURRENT_LIST_DIR}/mesh_neighbor_search_edge_mesh_float2d.cpp
  ${CMAKE_CURRENT_LIST_DIR}/mesh_neighbor_search_edge_mesh_float3d.cpp
  ${CMAKE_CURRENT_LIST_DIR}/mesh_neighbor_search_mesh.cpp
  ${CMAKE_CURRENT_LIST_DIR}/mesh_neighbor_search_mesh_double2d.cpp
  ${CMAKE_CURRENT_LIST_DIR}/mesh_neighbor_search_mesh_double3d.cpp
  ${CMAKE_CURRENT_LIST_DIR}/mesh_neighbor_search_mesh_float2d.cpp
  ${CMAKE_CURRENT_LIST_DIR}/mesh_neighbor_search_mesh_float3d.cpp
  ${CMAKE_CURRENT_LIST_DIR}/mesh_neighbor_search_point_cloud.cpp
  ${CMAKE_CURRENT_LIST_DIR}/point_cloud.cpp
  ${CMAKE_CURRENT_LIST_DIR}/point_cloud_fp.cpp
  ${CMAKE_CURRENT_LIST_DIR}/point_cloud_fp_double2d.cpp
  ${CMAKE_CURRENT_LIST_DIR}/point_cloud_fp_double3d.cpp
  ${CMAKE_CURRENT_LIST_DIR}/point_cloud_fp_float2d.cpp
  ${CMAKE_CURRENT_LIST_DIR}/point_cloud_fp_float3d.cpp
  ${CMAKE_CURRENT_LIST_DIR}/point_cloud_gather_ids_point_cloud.cpp
  ${CMAKE_CURRENT_LIST_DIR}/point_cloud_intersects_point_cloud.cpp
  ${CMAKE_CURRENT_LIST_DIR}/point_cloud_neighbor_search_point_cloud.cpp
  ${CMAKE_CURRENT_LIST_DIR}/prim_geometry_ops.cpp
  ${CMAKE_CURRENT_LIST_DIR}/prim_prim_ops.cpp
)
