services:
  web-example:
    build:
      context: .
      dockerfile: Dockerfile
    platform: linux/amd64
    environment:
      - ARTIFACTS_DIR=/workspace/web-examples/src/webAssembly/build/dist
    working_dir: /workspace
    volumes:
      - ../../../../:/workspace
    command: bash -lc ./web-examples/src/webAssembly/extras/build_web.sh
